routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('candidates', 'CandidatesController')->middleware('auth');
Route::get('candidates/changeuser/{cid}/{uid?}', 'CandidatesController@changeUser')->name('candidate.changeuser');
Route::get('candidates/changestatus/{cid}/{sid}', 'CandidatesController@changeStatus')->name('candidates.changestatus')->middleware('auth');

Route::get('mycandidates', 'CandidatesController@myCandidates')->name('candidates.mycandidates')->middleware('auth');

Route::resource('interviews', 'InterviewsController')->middleware('auth');
Route::get('interviews.view', 'InterviewsController@index')->name('interviews.view')->middleware('auth');
Route::get('interview.create', 'InterviewsController@create')->name('interview.create')->middleware('auth');
Route::get('interviews/changecandidate/{id}/{cid?}', 'InterviewsController@changecandidate')->name('interview.changecandidate')->middleware('auth');
Route::get('interview.choosecandidate', 'InterviewsController@chooseCandidate')->name('interview.choosecandidate')->middleware('auth');
Route::get('myinterviews', 'InterviewsController@myinterviews')->name('interviews.myinterviews')->middleware('auth');



Route::get('candidates/delete/{id}', 'CandidatesController@destroy')->name('candidate.delete');

Route::get('/hello', function (){
    return 'Hello Larevel';
}); 

Route::get('/student/{id}', function ($id  = 'No student found'){
    return 'We got student with id '.$id;
});

Route::get('/car/{id?}', function ($id  = null){
    if(isset($id)){
        //TODO: validate for integer  
        return "We got car $id";
    } else {
        return 'We need the id to find your car';
    }
});


Route::get('/comment/{id}', function ($id) {
    return view('comment', compact('id'));
});

Route::get('/users/{email}/{name?}', function ($email,$name = null) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});




#example
Route::get('/users1/{name?}/{email}', function ($name = null, $email) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});























Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/InterviewsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Candidate;
use App\User;
use App\Status;
use App\Interview;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Session;

class InterviewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $interviews = Interview::all();
        $candidates = Candidate::all();
        $users = User::all();
        
          
        return view('interviews.indexint', compact('interviews','candidates','users'));
    }

    public function changecandidate($id, $cid = null){
       
        $interview = Interview::findOrFail($id);
        $interview->candidate_id = $cid;
        $interview->save(); 
        return back();
        //return redirect('candidates');
        //comment
    }

    public function myinterviews()
    {        
        $userId = Auth::id();
        $user = User::findOrFail($userId);
        $interviews = $user->interviews;
        $candidates = Candidate::all();
 
             
        return view('interviews.indexint', compact('candidates','user', 'interviews'));
    
        
      
      
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        Gate::authorize('assign-user');
        Gate::authorize('assign-interview');
        $candidates=Candidate::all();
        $users=User::all();
        return view('interviews.createinterview', compact('candidates','users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $interview = new Interview();
        //$candidate->name = $request->name; 
        //$candidate->email = $request->email;
        $int = $interview->create($request->all());
        $int->save();
        return redirect('interviews');
    }

    

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/interviews/createinterview.blade.php
@extends('layouts.app')

@section('title', 'Create Interview')

@section('content')
        <h1>Create Interview</h1>
        <form method = "post" action = "{{action('InterviewsController@store')}}">
        @csrf 
        <div class="form-group">
            <label for = "summary">Interview summmary</label>
            <input type = "text" class="form-control" name = "summary">
        </div>  
        <div class="form-group">
            <label for = "date">Interview date</label>
            <input type = "text" class="form-control" name = "date">
        </div>    
        <label for="candidate_id" class="col-md-4 col-form-label text-md-right">Choose Candidate</label>
        <div class="col-md-6">
                        <select class="form-control" name="candidate_id">                                                                         
                          @foreach ($candidates as $candidate)
                          <option value="{{ $candidate->id }}"> 
                              {{ $candidate->name }} 
                          </option>
                          @endforeach    
                        </select>
                    
                            
                    </div>
         
        <div>
        <label for="user_id" class="col-md-4 col-form-label text-md-right">Choose Users</label>
        <div class="col-md-6">
                        <select class="form-control" name="user_id">                                                                         
                          @foreach ($users as $user)
                          <option value="{{ $user->id }}"> 
                              {{ $user->name }} 
                          </option>
                          @endforeach    
                        </select>
                    
                            
                    </div>
         
        <div>
            <input type = "submit" name = "submit" value = "Create interview">
        </div>                       
        </form>    
@endsection

resources/views/interviews/editinterview.blade.php
@extends('layouts.app')

@section('title', 'Edit candidate')

@section('content')       
       <h1>Edit candidate</h1>
        <form method = "post" action = "{{action('CandidatesController@update',$candidate->id)}}">
        @csrf
        @METHOD('PATCH')
        <div class="form-group">
            <label for = "name">Candiadte name</label>
            <input type = "text" class="form-control" name = "name" value = {{$candidate->name}}>
        </div>     
        <div class="form-group">
            <label for = "email">Candiadte email</label>
            <input type = "text" class="form-control" name = "email" value = {{$candidate->email}}>
        </div> 
        <div>
            <input type = "submit" name = "submit" value = "Update candidate">
        </div>                       
        </form>    
    </body>
</html>
@endsection

resources/views/interviews/indexint.blade.php
@extends('layouts.app')

@section('title', 'Candidates')

@section('content')
@if(Session::has('notallowed'))
<div class = 'alert alert-danger'>
    {{Session::get('notallowed')}}
</div>
@endif
<div> <a class="navbar-brand" href="{{ route('interviews.create') }}"> Add new Interview</a></div>
<h1>List of Interviews</h1>
<table class = "table table-dark">
    <tr>
        <th>id</th><th>Summary</th><th>Date</th><th>Candidate</th><th>User</th><th>Created</th><th>Updated</th>
    </tr>
    <!-- the table data -->
    @foreach($interviews as $interview)
        <tr>
            <td>{{$interview->id}}</td>
            <td>{{$interview->summary}}</td>
            <td>{{$interview->date}}</td>
          
            <td>
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        @if(isset($interview->candidate_id))
                          {{$interview->candidates->name}}  
                        @else
                          Assign Candidate
                        @endif
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    @foreach($candidates as $candidate)
                      <a class="dropdown-item" href="{{route('interview.changecandidate',[$interview->id,$candidate->id])}}">{{$candidate->name}}</a>
                    @endforeach
                    </div>
                  </div>                
            </td> 
           <td>
            @if(isset($interview->user_id))
                {{$interview->users->name}}  
            @else
                no Interviewer yet
            @endif
            </td>

                             
            <td>{{$interview->created_at}}</td>
            <td>{{$interview->updated_at}}</td>
            
    @endforeach
</table>
@endsection

resources/views/interviews/nointerviews.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Comment</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet">

        <!-- Styles -->
        <style>
            html, body {
                background-color: #fff;
                color: #636b6f;
                font-family: 'Nunito', sans-serif;
                font-weight: 200;
                height: 100vh;
                margin: 0;
            }

            .full-height {
                height: 100vh;
            }

            .flex-center {
                align-items: center;
                display: flex;
                justify-content: center;
            }

            .position-ref {
                position: relative;
            }

            .top-right {
                position: absolute;
                right: 10px;
                top: 18px;
            }

            .content {
                text-align: center;
            }

            .title {
                font-size: 84px;
            }

            .links > a {
                color: #636b6f;
                padding: 0 25px;
                font-size: 13px;
                font-weight: 600;
                letter-spacing: .1rem;
                text-decoration: none;
                text-transform: uppercase;
            }

            .m-b-md {
                margin-bottom: 30px;
            }
        </style>
    </head>
    <body>
            <div class="content">
                <div class="title m-b-md">
                    No Interviews
            </div>
    </body>
</html>